#!/bin/bash

REPO=~/dev/dotfiles

cd ~

# Bash
cp -v .bash_profile .bashrc .profile $REPO/

# Zsh
cp -v .zlogin .zshrc $REPO/

# Local scripts
cp -v -r .bin $REPO/

# Xorg and misc
cp -v .xinitrc .xmobarrc .Xmodmap .Xresources .compton.conf $REPO/

# Xorg (global)
cp -v /etc/X11/xorg.conf $REPO/etc/X11/

# Intel Driver
cp -v /etc/X11/xorg.conf.d/20-intel.conf $REPO/etc/X11/xorg.conf.d/20-intel.conf

# Xmonad
cp -v .xmonad/xmonad.hs $REPO/.xmonad/

# Pacman
cp -v /etc/pacman.conf $REPO/etc/

# Screensaver
cp -v .xscreensaver $REPO/

# Vim Settings
cp -v .vimrc $REPO/

# SSH Completion
cp -v .ssh_completion_zsh $REPO/
